### ISSUE TITLE
Create timestamps of the video Deprecations

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy-newsletter#16]
Create timestamps of the video recording of Sebastian’s presentation _Maintaining NumPy: Deprecations_: https://www.youtube.com/watch?v=DjiC4-8c5f0.

**Comment by Bennykillua** [comment]
@InessaPawson  I would like to work on this PR

**Comment by InessaPawson** [comment]
@Bennykillua Fantastic! Please submit the timestamps to this file: https://github.com/numpy/numpy-newsletter/blob/main/youtube-timestamps/timestamps-2022-06-02.md
I'll add them to the video description on YouTube.

**Comment by Bennykillua** [comment]
Here is the [PR](https://github.com/numpy/numpy-newsletter/pull/17) for the [Maintaining NumPy: Deprecations :: Sebastian Berg](Maintaining NumPy: Deprecations :: Sebastian Berg) task @InessaPawson
