### ISSUE TITLE
Create timestamps of the video Browse and debug NumPy core files with vim, ctags, and cscope

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy-newsletter#20]
Create timestamps of the video *Browse and debug NumPy core files with vim, ctags, and cscope*: https://www.youtube.com/watch?v=VXxa3G4BtEc

**Comment by JulesKouatchou** [comment]
I watched the video (but have not edited it yet) and here is my proposed timestamps:

- 00:00 Outline of the presentation
- 01:04 Self-introduction of the speaker
- 01:24 Brief agenda
- 01:52 Shell session with environment settings
- 04:32 Brief introduction to the `hex` function
- 05:36 Features of `vim` (to open several files)
- 09:15 Features of `ctags` and `cscope`
- 14:32 Q/A on environment settings
- 19:30 Preparation for debugging
- 26:08 Using `gdb` for debugging
- 30:06 Q/Q on how to navigate frames to extract variables
- 31:35 Resume using `gdb`
- 36:08 Start fixing the bug
- 38:45 Live debugging with `gdb`
- 39:49 Q/A on debugging context
- 42:48 Resume live debugging
- 45:28 Brief introduction to `Py-bt`
- 45:51 Feedback and comments from participants

If the above is fine, I will add the timestamps to the video

**Comment by InessaPawson** [comment]
@JulesKouatchou This is great! Please submit a PR.
