### ISSUE TITLE
Create timestamps of the video Design jam session on the NumPy contributor journey map 

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy-newsletter#24]
Create timestamps of the video _Design jam session on the NumPy contributor journey map_: https://www.youtube.com/watch?v=QhrqPr0TNrs.

**Comment by JulesKouatchou** [comment]
Here is what I plan to include in the video:

- 00:00 Introduction and welcoming remarks
- 00:54 What is NumPy newcomers' hour?
- 01:30 What are jamming today?
- 01:43 Design Jam Session 1
- 02:27 Why are we jamming?
- 03:55 Design Jam Session 2
- 04:37 Closing remarks

**Comment by InessaPawson** [comment]
@JulesKouatchou Looks good! Please submit a PR.
