### ISSUE TITLE
Create timestamps of the video NumPy in the classroom

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy-newsletter#25]
Create timestamps of the video _NumPy in the classroom_: https://www.youtube.com/watch?v=lHDEr2eCjAM.

**Comment by JulesKouatchou** [comment]
Here is what I am proposing for video editing (will submit a PR):

- 00:00 Statement on the NumPy Code of Conduct
- 01:04 Introduction of the speaker
- 02:10 Self-introduction of each participant
- 06:05 Beginning of slide presentation and general benefit of NumPy
- 08:03 Self-introduction of the speaker
- 09:01 Accessing current presentation and other resources
- 10:02 Why use NumPy in Mechanical Engineering courses?
- 12:54 Exercises: questions to participants and speaker's comments
- 27:55 Diagram on Learner's Journey
- 29:45 Presentation of an open educational resource in Computational Mechanics
- 35:26 Revisiting the Learner's Journey
- 26:14 NumPy in Mechanical Engineering
- 41:37 Benefits of NumPy: Products
- 42:35 Benefits of NumPy: Experience

**Comment by InessaPawson** [comment]
@JulesKouatchou This is great! Please submit a PR. Going forward, feel free to share your ideas directly in a PR, no need to comment in the issue first. Thank you again for picking up these issues!
