### ISSUE TITLE
Create timestamps of the video Ufuncs and dtypes: New possibilities in NumPy

### ISSUE THREAD

**Issue by InessaPawson** [numpy/numpy-newsletter#26]
Create timestamps of the video _Ufuncs and dtypes: New possibilities in NumPy_: https://www.youtube.com/watch?v=u9qU6cy5JkE.

**Comment by JulesKouatchou** [comment]
Here is what I propose:

- 00:00 Self-introduction of the the speaker
- 00:37 Motivation of the work
- 02:05 NumPy Dtypes: Example UnitDType
- 04:32 What is a UFunc?
- 08:42 Lets make a UFunc: The "strided loop"
- 12:25 Lets make a UFunc: The "Resolver"
- 15:31 Let make a UFunc: Wrap it up!
- 18:42 Done with UFunc!
- 18:56 How do casts work?
- 20:26 What makes the UnitDType?
- 25:42 Summary and acknowledgements
- 27:24 Q/A session

If the above is fine, I will edit the video.

**Comment by InessaPawson** [comment]
@JulesKouatchou The proposed timestamps look great! Please submit a PR to this repo. Here is an example of a similar PR for your reference: https://github.com/numpy/numpy-newsletter/pull/21.

**Comment by JulesKouatchou** [comment]
I am still trying to figure out how to add timestamps on videos I do not own. I am wondering if I need to copy video in my channel first or I need to access YouTube through the NumPy account.

**Comment by InessaPawson** [comment]
@JulesKouatchou Yes, the access to the NumPy YouTube account is required for it. I'll add the timestamps to the video descriptions on YouTube manually.

**Comment by Mukulikaa** [comment]
Completed via #27.
